export ARCH=arm
export CROSS_COMPILE=~/core/build/out-glibc/sysroots/x86_64-linux/usr/bin/arm-angstrom-linux-gnueabi/arm-angstrom-linux-gnueabi-
export CPLUS_INCLUDE_PATH=/home/maurice/aws-sdk-cpp/testing-resources/include:/home/maurice/aws-sdk-cpp/aws-cpp-sdk-core/include:/home/maurice/aws-sdk-cpp/aws-cpp-sdk-dynamodb/include:~/aws-sdk-cpp/aws-cpp-sdk-s3/include:~/aws-sdk-cpp/aws-cpp-sdk-transfer/include:~/aws-sdk-cpp/aws-cpp-sdk-cognito-identity/include:~/aws-sdk-cpp/aws-cpp-sdk-access-management/include:~/aws-sdk-cpp/aws-cpp-sdk-identity-management/include:~/aws-sdk-cpp/aws-cpp-sdk-cognito-sync/include:~/aws-sdk-cpp/aws-cpp-sdk-sts/include
export C_INCLUDE_PATH=/home/maurice/aws-sdk-cpp/testing-resources/include:/home/maurice/aws-sdk-cpp/aws-cpp-sdk-core/include:/home/maurice/aws-sdk-cpp/aws-cpp-sdk-dynamodb/include:~/aws-sdk-cpp/aws-cpp-sdk-transfer/include:~/aws-sdk-cpp/aws-cpp-sdk-cognito-identity/include:~/aws-sdk-cpp/aws-cpp-sdk-access-management/include:~/aws-sdk-cpp/aws-cpp-sdk-identity-management/include:~/aws-sdk-cpp/aws-cpp-sdk-cognito-sync/include:~/aws-sdk-cpp/aws-cpp-sdk-sts/include
export LIBRARY_PATH=/home/maurice/aws-sdk-cpp/aws-cpp-sdk-core:/home/maurice/aws-sdk-cpp/aws-cpp-sdk-dynamodb:~/aws-sdk-cpp/aws-cpp-sdk-s3:~/aws-sdk-cpp/aws-cpp-sdk-transfer:~/aws-sdk-cpp/aws-cpp-sdk-cognito-identity:~/aws-sdk-cpp/aws-cpp-sdk-access-management:~/aws-sdk-cpp/aws-cpp-sdk-identity-management:~/aws-sdk-cpp/aws-cpp-sdk-cognito-sync:~/aws-sdk-cpp/aws-cpp-sdk-sts:~/aws-sdk-cpp/corelib
${CROSS_COMPILE}g++ -DAWS_CUSTOM_MEMORY_MANAGEMENT -std=c++11 -mfloat-abi=hard -L/home/maurice/aws-sdk-cpp/aws-cpp-sdk-core -L/home/maurice/aws-sdk-cpp/aws-cpp-sdk-dynamodb -L/home/maurice/aws-sdk-cpp/aws-cpp-sdk-s3 -L/home/maurice/aws-sdk-cpp/aws-cpp-sdk-transfer -L/home/maurice/aws-sdk-cpp/aws-cpp-sdk-access-management -L/home/maurice/aws-sdk-cpp/aws-cpp-sdk-cognito-identity -L/home/maurice/aws-sdk-cpp/aws-cpp-sdk-identity-management -L/home/maurice/aws-sdk-cpp/aws-cpp-sdk-cognito-sync -L/home/maurice/aws-sdk-cpp/aws-cpp-sdk-sts -L/home/maurice/aws-sdk-cpp/corelib -o $3 $1 $2 -l$4 -l$5 -l$6 -l$7 -l$8 -l$9 -laws-cpp-sdk-cognito-sync -laws-cpp-sdk-cognito-identity -laws-cpp-sdk-sts -lcurl



